=== LolaRennt/s-tea/target/classes/page.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/page" xmlns:tns="http://www.example.org/page" elementFormDefault="qualified">

    <element name="elements" type="tns:elements"></element>
    
    <element name="frame" type="tns:frame"></element>
    
    <element name="element" type="tns:element"></element>
    
    <element name="childElement" type="tns:childelement"></element>
    
    <complexType name="elements">
    	<sequence maxOccurs="unbounded" minOccurs="0">
    		<element ref="tns:element" maxOccurs="unbounded"
    			minOccurs="0">
    		</element>
    		<element ref="tns:frame" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    		<element ref="tns:list" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="element">
    	<sequence maxOccurs="1" minOccurs="0">
    		<element ref="tns:childElement" maxOccurs="1"
    			minOccurs="0">
    		</element>
    	</sequence>
    	<attribute name="id" type="string" use="required"></attribute>
    	<attribute name="by" use="required">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="id"></enumeration>
    				<enumeration value="xpath"></enumeration>
    				<enumeration value="name"></enumeration>
    				<enumeration value="linkText"></enumeration>
    				<enumeration value="css"></enumeration>
    				<enumeration value="partialLinkText"></enumeration>
    				<enumeration value="class"></enumeration>
    				<enumeration value="tagName"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    	<attribute name="value" type="string" use="required"></attribute>
    	<attribute name="index" type="string" default="0"
    		use="optional">
    	</attribute>
    	<attribute name="type" use="optional" default="element">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="element"></enumeration>
    				<enumeration value="button"></enumeration>
    				<enumeration value="checkBox"></enumeration>
    				<enumeration value="comoboBox"></enumeration>
    				<enumeration value="image"></enumeration>
    				<enumeration value="label"></enumeration>
    				<enumeration value="link"></enumeration>
    				<enumeration value="listElement"></enumeration>
    				<enumeration value="radioButton"></enumeration>
    				<enumeration value="richTextField"></enumeration>
    				<enumeration value="table"></enumeration>
    				<enumeration value="textField"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    </complexType>

    <complexType name="childelement">
    	<sequence maxOccurs="1" minOccurs="0">
    		<element ref="tns:childElement"></element>
    	</sequence>
    	<attribute name="by" use="required">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="id"></enumeration>
    				<enumeration value="css"></enumeration>
    				<enumeration value="class"></enumeration>
    				<enumeration value="tagName"></enumeration>
    				<enumeration value="linkText"></enumeration>
    				<enumeration value="name"></enumeration>
    				<enumeration value="partialLinkText"></enumeration>
    				<enumeration value="xpath"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    	<attribute name="index" type="string" default="0" use="optional"></attribute>
    	<attribute name="value" type="string" use="required"></attribute>
    </complexType>

    <complexType name="frame">
    	<sequence minOccurs="0" maxOccurs="1">
    		<element ref="tns:element" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    	<attribute name="id" type="string" use="required"></attribute>
    	<attribute name="by" use="required">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="id"></enumeration>
    				<enumeration value="xpath"></enumeration>
    				<enumeration value="css"></enumeration>
    				<enumeration value="class"></enumeration>
    				<enumeration value="name"></enumeration>
    				<enumeration value="tagName"></enumeration>
    				<enumeration value="linkText"></enumeration>
    				<enumeration value="partialLinkText"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    	<attribute name="value" type="string" use="required"></attribute>
    	<attribute name="index" type="string" use="optional" default="0"></attribute>
    </complexType>

    

    <element name="list" type="tns:list"></element>

    
    <complexType name="list">
    	<sequence maxOccurs="unbounded">
    		<element ref="tns:frame" minOccurs="0" ></element>
    		<element ref="tns:element" minOccurs="0"></element>
    	</sequence>
    	<attribute name="id" type="string"></attribute>
    </complexType>
</schema>

=== LolaRennt/s-tea/target/classes/source.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:elements xmlns:tns="http://www.example.org/page" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/page page.xsd ">
	<tns:element value="kw" by="id" id="百度首页-搜索框"/>
	<tns:element value="su" by="id" id="百度首页-搜索按钮"/>
	<tns:element value="ddl_game" by="id" id="测评游戏" />
	<tns:element value="ddl_mode" by="id" id="测评模式" />
	<tns:element value=".//*[@id='div_gpuTop']/div[1]/div[2]/div" by="xpath" id="测评得分"></tns:element>
	<tns:element value=".//*[@id='div_gpuTop']/div[1]/div[3]/div/a" by="xpath" id="测评显卡均价"></tns:element>
	<tns:element value="w760" by="class" id="MW-平板列表-苹果">
    	<tns:childElement value="dd" by="tagName" index="1">
      		<tns:childElement value="苹果" by="linkText"/>
    	</tns:childElement>
  </tns:element>
  <tns:list id="">
      <tns:element value="" by="id" id=""></tns:element>
  </tns:list>
</tns:elements>
